name: Publish slides and notebooks

on: 
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install -r requirements.txt

      - name: Set up quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - run: |
          quarto render --to html
          quarto render --to ipynb
      - name: Archive build as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sitedir
          path: |
            _site
      - name: Publish to Pages
        if: github.ref == 'refs/heads/main'
        run: |
          git config --global user.email quarto-github-actions-publish@example.com
          git config --global user.name "Quarto GHA Workflow Runner"
          quarto publish gh-pages . --no-render --no-browser