name: Publish slides and notebooks

on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up quarto
        uses: quarto-dev/quarto-actions/setup@v2
      - run: |
          quarto render --to html
#           quarto render resources/python.qmd --to ipynb
      - name: Publish to GitHub Pages (and render)
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          render: false
          target: gh-pages